# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-08 02:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u5206\u7ec4\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='BlockPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u540d\u5b57')),
                ('desp', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
                ('bounding', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='\u63a2\u6d4b\u591a\u8fb9\u5f62')),
            ],
        ),
        migrations.AddField(
            model_name='blockgroup',
            name='blocks',
            field=models.ManyToManyField(to='geoinfo.BlockPolygon', verbose_name='\u5305\u542b\u533a\u57df'),
        ),
    ]
