# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.ManyToManyField(blank=True, to='geoinfo.BlockPolygon', verbose_name='\u5305\u542b\u533a\u57df')),
            ],
        ),
        migrations.AlterField(
            model_name='blockgroup',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='geoinfo.BlockPolygon', verbose_name='\u5305\u542b\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='dispatched',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geoinfo.BlockGroup'),
        ),
    ]
