# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-11 08:25
from __future__ import unicode_literals

from django.db import migrations
import helpers.base.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0002_auto_20180111_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatched',
            name='blocks',
        ),
        migrations.AddField(
            model_name='dispatched',
            name='blocks',
            field=helpers.base.jsonfield.JsonField(default=[], verbose_name='\u5df2\u9009\u62e9\u533a\u57df'),
        ),
    ]
