# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-07 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0004_dispatched_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatched',
            name='last_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 2, 7, 6, 43, 32, 83000, tzinfo=utc), verbose_name='\u4e0a\u6b21\u751f\u6210\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
