# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0005_dispatched_last_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpolygon',
            name='shot',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u622a\u56fe'),
        ),
    ]
